EventCard_Project/EventCard/urls.py
from django.conf.urls import patterns, url

from EventCard import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^login$', views.user_login, name='user_login'),
	url(r'^logout$', views.user_logout, name='user_logout'),
	url(r'^signup$', views.user_signup, name='user_signup'),
	url(r'^events$', views.events, name='events')
)

EventCard_Project/EventCard_Project/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'EventCard_Project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^', include('EventCard.urls', namespace='EventCard')),
    url(r'^admin/', include(admin.site.urls), name='admin'),
)

EventCard_Project/EventCard/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
	# This line is required. Links UserProfile to a User model instance.
	user = models.OneToOneField(User)

	# The additional attributes we wish to include.
	description = models.CharField(max_length=200, blank=True)

	# Override the __unicode__() method to return out something meaningful!
	def __unicode__(self):
		return self.user.username

EventCard_Project/EventCard/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse

from EventCard.models import UserProfile

def index(request):
	if request.user.is_authenticated():
		return redirect(reverse('EventCard:events'))
	else:
		return render(request, 'EventCard/index.html')

def user_signup(request):
	if request.method == 'POST':
		email = request.POST['email']
		password = request.POST['password']	
		if not User.objects.filter(username=email).exists():
			user = User.objects.create_user(email, email, password)
			user.first_name = request.POST['first_name']
			user.last_name = request.POST['last_name']
			user.save()
			profile = UserProfile()
			profile.user = user
			profile.description = request.POST['description']
			profile.save()
			user = authenticate(username=email, password=password)
			login(request, user)
			return redirect(reverse('EventCard:events'))
		else:
			return render(request, 'EventCard/signup.html', {'message':'Email exists! Try another one...'})
	else:
		return render(request, 'EventCard/signup.html')

def user_login(request):
	if request.method == 'POST':
		username = request.POST['email']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user:
			login(request, user)
			return redirect(reverse('EventCard:events'))
		else:
			return render(request, 'EventCard/login.html', {'message':'Email or Password is invalid!'})
	else:
		return render(request, 'EventCard/login.html')

def user_logout(request):
	logout(request)
	return redirect(reverse('EventCard:index'))

def events(request):
	return render(request, 'EventCard/events.html')

EventCard_Project/EventCard/templates/EventCard/events.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<!-- Favicon -->
	<link rel="shortcut icon" href="#">

	<!-- CSS Global Compulsory -->
	<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

	<title>Events for EventCard</title>

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
  </head>

  <body>

	<div class="container page-index">
		{% if user.is_authenticated %}
		<h4>Welcome {{user.email}}</h4>
	  	{% endif %}
	  	<a href="{% url 'EventCard:user_logout' %}">Logout</a>

	</div> <!-- /container -->


	<!-- Bootstrap core JavaScript
	================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

EventCard_Project/EventCard/templates/EventCard/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<!-- Favicon -->
	<link rel="shortcut icon" href="#">

	<!-- CSS Global Compulsory -->
	<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

	<title>Index for EventCard</title>

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
  </head>

  <body>

	<div class="container page-index">

		<h4>Welcome to EventCard!</h1>
	  	<ul class="list-group">
	  		<li class="list-group-item"><a href="{% url 'EventCard:user_signup' %}">Sign Up</a></li>
	    	<li class="list-group-item"><a href="{% url 'EventCard:user_login' %}">Log In</a></li>
	  	</ul>

	</div> <!-- /container -->


	<!-- Bootstrap core JavaScript
	================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

EventCard_Project/EventCard/templates/EventCard/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<!-- Favicon -->
	<link rel="shortcut icon" href="#">

	<!-- CSS Global Compulsory -->
	<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

	<title>Login for EventCard</title>

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
  </head>

  <body>

	<div class="container page-index">

		<h4><a href="{% url 'EventCard:index' %}">Welcome to EventCard!</h1></a>
	  	<form action="{% url 'EventCard:user_login' %}" method="post" class="form-signin" role="form">
	  		{% csrf_token %}
        	<h2 class="form-signin-heading">Please log in</h2>
        	<div class="form-group">
    			<label>Email address</label>
    			<input type="email" name="email" class="form-control" placeholder="Email address" required autofocus>
  			</div>
  			<div class="form-group">
    			<label>Password</label>
    			<input type="password" name="password" class="form-control" placeholder="Password" required>
  			</div>
  			{% if message %}
  			<div class="alert alert-danger">{{ message }}</div>
  			{% endif %}
  			<div class="checkbox">
    			<label>
      				<input type="checkbox"> Remember me
    			</label>
  			</div>
        	<button class="btn btn-lg btn-primary btn-block" type="submit">Log In</button>
      	</form>

	</div> <!-- /container -->


	<!-- Bootstrap core JavaScript
	================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script type="text/javascript" src="{% static 'assets/js/validation.js' %}"></script>
  </body>
</html>

EventCard_Project/EventCard/templates/EventCard/signup.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<!-- Favicon -->
	<link rel="shortcut icon" href="#">

	<!-- CSS Global Compulsory -->
	<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

	<title>Signup for EventCard</title>

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
  </head>

  <body>

	<div class="container page-index">

		<a href="{% url 'EventCard:index' %}"><h4>Welcome to EventCard!</h1></a>
	  	<form action="{% url 'EventCard:user_signup' %}" method="post" class="form-signup" role="form">
	  		{% csrf_token %}
        	<h2 class="form-signup-heading">Please sign up</h2>
        	<div class="form-group">
    			<label>Email address</label>
    			<input type="email" name="email" class="form-control" placeholder="Email address" required autofocus>
  			</div>
  			{% if message %}
  			<div class="alert alert-danger">{{ message }}</div>
  			{% endif %}
  			<div class="form-group">
    			<label>Password</label>
    			<input type="password" name="password" class="form-control" placeholder="Password" required>
  			</div>
  			<div class="form-group">
    			<label>Conform Password</label>
    			<input type="password" name="password_confirm" class="form-control" placeholder="Confirm Password" required>
  			</div>
  			<div class="form-group">
    			<label>First Name (Optional)</label>
    			<input type="text" name="first_name" class="form-control" placeholder="First Name" >
  			</div>
  			<div class="form-group">
    			<label>Last Name (Optional)</label>
    			<input type="text" name="last_name" class="form-control" placeholder="Last Name" >
  			</div>
  			<div class="form-group">
    			<label>Self Description (Optional)</label>
    			<input type="text" name="description" class="form-control" placeholder="Description" >
  			</div>        	
        	<button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
      	</form>

	</div> <!-- /container -->


	<!-- Bootstrap core JavaScript
	================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>